# Generated by Django 5.0.7 on 2024-08-01 15:13

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_alter_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='info',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
